### PR TITLE
Detached digest algorithms are from COSE registry

### PR DESCRIPTION
**Pull request by laurencelundblade**

### CODE REVIEW

**Comment by laurencelundblade** [comment]
Address #246

**Comment by gmandyam** [comment]
JOSE also has its own registry:  https://www.iana.org/assignments/jose/jose.xhtml#web-signature-encryption-algorithms.  For JWT variants of EAT/DEB do we consider these identifiers instead?

**Comment by laurencelundblade** [comment]
I excluded the JOSE registry intentionally because a) it has no hash functions registered and b) detached digests are not particularly bound to whether the token is JSON or CBOR.

**Comment by gmandyam** [comment]
@laurencelundblade 

> excluded the JOSE registry intentionally because a) it has no hash functions registered

Don't understand the above.  The first 3 entries in the JOSE registry are HMAC algm.'s,.  Or is the assertion that MAC's are never suitable for the DEB digest?

**Comment by laurencelundblade** [comment]
Yes, it needs a hash algorithm, not an HMAC.

**Comment by gmandyam** [comment]
>Yes, it needs a hash algorithm, not an HMAC.

If that is the case, then the text needs to be clarified that only hash algm.'s (and not MAC's) are suitable candidates from the COSE algm. registry.  HMAC's as digests comes up in different places, and an independent reader/implementer may not know the difference.

**Comment by gmandyam** [comment]
Satisfied with PR now.  Please merge (unless there are other reviewers).

**Pull request merged**
